external_data_source:
  cassendra_db: data/external/train.csv

raw_data_config: 
  raw_data_csv: data/raw/train.csv

processed_data_config:
  train_test_split_ratio: 0.2
  random_state: 45
  target: labels 
  processed_data_csv: data/processed/processed_data.csv
  train_data_csv: data/processed/news_train.csv
  test_data_csv:  data/processed/news_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: svm
  registered_model_name: svm_model
  remote_server_uri: http://localhost:1234

svm_model: 
  kernel: 'rbf'
  gamma: 0.1
  C: 10
 
model:
  model_dir: models/model.joblib
  params_dir : reports/params.json
  score_dir : reports/score.json
  vectorizer_dir: models/vectorizer.joblib



model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html